CREATE TABLE [dbo].[VisitorCards]
(
	[VisitorCardId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [ChurchId] UNIQUEIDENTIFIER NOT NULL, 
    [VisitorFirstName] NVARCHAR(MAX) NULL,
    [VisitorLastName] NVARCHAR(MAX) NULL,
    [VisitorEmail] NVARCHAR(MAX) NULL,
    [VisitorPhone] NVARCHAR(MAX) NULL,
    [VisitorAddress] NVARCHAR(MAX) NULL,
    [VisitorCity] NVARCHAR(MAX) NULL,
    [VisitorState] NVARCHAR(MAX) NULL, 
    [VisitorZip] NVARCHAR(MAX) NULL, 
    [VisitorAge] int null,
    [DateOfAttendance] datetime null,
    [IsNewToArea] bit NOT null DEFAULT 0,
    [IsExistingChristian] bit NOT null DEFAULT 0,
    [IsReturningVisitor] bit NOT null DEFAULT 0,
    [ReferralType] int null,
    [ReasonForAttendance] NVARCHAR(MAX) NULL, 
    [Comments] NVARCHAR(MAX) NULL,
    [HomeChurch] NVARCHAR(MAX) NULL,
    [IsFirstTimeGuest] bit NOT null DEFAULT 0,
    CONSTRAINT [PK_VisitorCard] PRIMARY KEY CLUSTERED ([VisitorCardId] ASC),
    CONSTRAINT [FK_VisitorCard_Church] FOREIGN KEY ([ChurchId]) REFERENCES [dbo].[Churches] ([ChurchId]),
)
