// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchService.Library.SQL
{
    public partial class ErrorLog
    {
        public Guid ErrorLogId { get; set; }
        public Guid? ParentErrorLogId { get; set; }
        public string ExceptionMessage { get; set; }
        public string StackTrace { get; set; }
        public DateTime TimeStamp { get; set; }
        public Guid? UserId { get; set; }
        public string UserIpAddress { get; set; }
        public string ViewModel { get; set; }
        public string Url { get; set; }
    }
}