// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChurchService.Library.SQL
{
    public partial class GetAvailableMembersResult
    {
        public Guid UserId { get; set; }
        public string FullName { get; set; }
    }
}
