// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChurchService.Library.SQL;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ChurchService.Library.SQL
{
    public partial interface IChurchServiceContextProcedures
    {
        Task<List<GetAvailableMembersResult>> GetAvailableMembersAsync(DateTime? visitDate, Guid? churchId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<testResult>> testAsync(Guid? churchId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
