// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchService.Library.SQL
{
    public partial class PlannedVisit
    {
        public Guid PlannedVisitId { get; set; }
        public Guid ChurchId { get; set; }
        public Guid? AssignedUserId { get; set; }
        public DateTime VisitDate { get; set; }
        public string VisitorFirstName { get; set; }
        public string VisitorLastName { get; set; }
        public string VisitorPhone { get; set; }
        public string VisitorEmail { get; set; }
        public string CommentsOrQuestions { get; set; }

        public virtual User AssignedUser { get; set; }
        public virtual Church Church { get; set; }
    }
}