// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchService.Library.SQL
{
    public partial class UnavailableDate
    {
        public Guid UnavailableDateId { get; set; }
        public Guid UserId { get; set; }
        public DateTime DateUnavailable { get; set; }

        public virtual User User { get; set; }
    }
}