// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchService.Library.SQL
{
    public partial class UserSmsVerification
    {
        public Guid UserSmsVerificationId { get; set; }
        public Guid UserId { get; set; }
        public string PhoneNumber { get; set; }
        public bool Verified { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime Expiration { get; set; }
        public bool Active { get; set; }
        public int VerificationCode { get; set; }

        public virtual User User { get; set; }
    }
}